# -*- coding: utf-8 -*-
"""Healthcare_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDkD_sxrSKt5OD4NXqno0gJN7b3rTRoH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

np.random.seed(0)

num_patients = 10000

data = {
    "Patient_ID": np.random.choice(np.arange(10000, 99999), size=10000, replace=False),
    "Age": np.random.randint(20, 81, num_patients),
    "Gender": np.random.choice(["Male", "Female"], num_patients),
    "Blood_Pressure": np.random.randint(80, 181, num_patients),
    "Sugar_Level": np.random.randint(70, 201, num_patients),
    "Cholesterol": np.random.randint(150, 301, num_patients),
    "Heart_Rate": np.random.randint(60, 121, num_patients)
}

data = pd.DataFrame(data)
data

print("Means:\n")
print(data[['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']].mean())

print("Medians:\n")
print(data[['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']].median())

print("Modes:\n")
print(data[['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']].mode().iloc[0])

def classify_risk(row):
    risk_score = 0

    if row["Blood_Pressure"] > 140:
        risk_score += 1
    if row["Sugar_Level"] > 160:
        risk_score += 1
    if row["Cholesterol"] > 240:
        risk_score += 1
    if row["Heart_Rate"] > 100:
        risk_score += 1

    if risk_score >= 3:
        return "High"
    elif risk_score == 2:
        return "Medium"
    else:
        return "Low"

data["Risk_Level"] = data.apply(classify_risk, axis=1)
data

plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
sns.histplot(data["Blood_Pressure"], bins=30, kde=True)
plt.title("Blood Pressure Distribution")

plt.subplot(2,2,2)
sns.histplot(data["Sugar_Level"], bins=30, kde=True)
plt.title("Sugar Level Distribution")

plt.subplot(2,2,3)
sns.histplot(data["Cholesterol"], bins=30, kde=True)
plt.title("Cholesterol Distribution")

plt.subplot(2,2,4)
sns.histplot(data["Heart_Rate"], bins=30, kde=True)
plt.title("Heart Rate Distribution")

plt.tight_layout()
plt.show()

data["Risk_Level"].value_counts()

high_risk_patients = data[data["Risk_Level"] == "High"]

high_risk_patients

age_risk_table = data.groupby("Age")["Risk_Level"].value_counts().unstack()

age_risk_table

gender_risk = data.groupby("Gender")["Risk_Level"].value_counts().unstack()
gender_risk

plt.figure()

gender_risk.plot(kind="bar")

plt.title("Gender-wise Health Risk Comparison")
plt.xlabel("Gender")
plt.ylabel("Number of Patients")

plt.show()

plt.figure()
data["Risk_Level"].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Risk Level Distribution")
plt.ylabel("")
plt.show()

plt.figure()
plt.scatter(data["Age"], data["Blood_Pressure"])
plt.title("Blood Pressure vs Age")
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.show()

plt.figure()
plt.scatter(data["Age"], data["Blood_Pressure"])
plt.title("Blood Pressure vs Age")
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.show()

plt.figure()

sugar_risk.plot(kind="bar")

plt.title("Average Sugar Level vs Risk Category")
plt.xlabel("Risk Category")
plt.ylabel("Average Sugar Level")

plt.show()

print("Total Patients:", len(data))
print("Medium Risk Patients:", len(data[data["Risk_Level"]=="High"]))
print("Medium Risk Patients:", len(data[data["Risk_Level"]=="Medium"]))
print("Low Risk Patients:", len(data[data["Risk_Level"]=="Low"]))

data.to_csv("healthcare_patient_data.csv", index=False)
print("Dataset saved successfully")